<?php
$data = array (
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '服装类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '26',
    'name' => '服装类',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '女装',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '女装',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '男装',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '男装',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '童装',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '童装',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '内衣',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '内衣',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '鞋包配饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '鞋包配饰',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '旅行箱包',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '旅行箱包',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '男包',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '男包',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '女包',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '女包',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '女鞋',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '15',
    'name' => '女鞋',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '男鞋',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '14',
    'name' => '男鞋',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '配饰',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => '配饰',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '运动户外',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '运动户外',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '运动服',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '运动服',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '运动鞋',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '8',
    'name' => '运动鞋',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '户外及装备',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '11',
    'name' => '户外及装备',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '数码',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 1,
    'id' => '5',
    'name' => '手机',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '电脑配件',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '4',
    'name' => '电脑配件',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '办公',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 1,
    'id' => '3',
    'name' => '办公',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'CDMA手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => 'CDMA手机',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '家电',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '家电',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '美容美发',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '美容美发',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '母婴用品',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '家居建材',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '家居建材',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '美食特产',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '20',
    'name' => '美食特产',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '日用百货',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '21',
    'name' => '日用百货',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '汽车/车品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '22',
    'name' => '汽车/车品',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '文化娱乐',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '23',
    'name' => '文化娱乐',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '图书音像',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '24',
    'name' => '图书音像',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '个性定制',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '个性定制',
  ),
);
?>